### ISSUE TITLE
Did you train you net ?

### ISSUE THREAD

**Issue by xue1liu2** [iwyoo/tf_DenseNet#1]
Did you got the expected results as  the author did?

**Comment by iwyoo** [comment]
No, not actually. I didn't test this source on cifar-10 dataset. I checked only on MNIST dataset with Adam optimizer, and it looks work fine. However, I'm not sure that this implementation gives same result with the authors'. I implemented this code to change detail-setting as easy as possible. (growth rate, layer per block, etc.)
